/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MateriRouteImport } from './routes/materi'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as MateriIndexRouteImport } from './routes/materi.index'
import { Route as MateriSlugRouteImport } from './routes/materi.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriRoute = MateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const MateriIndexRoute = MateriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MateriRoute,
} as any)
const MateriSlugRoute = MateriSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MateriRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/materi': typeof MateriRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/materi/': typeof MateriIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/materi': typeof MateriIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/materi': typeof MateriRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/services': typeof ServicesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/materi/$slug': typeof MateriSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/materi/': typeof MateriIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/contact'
    | '/materi'
    | '/portfolio'
    | '/services'
    | '/articles/$slug'
    | '/materi/$slug'
    | '/portfolio/$slug'
    | '/articles/'
    | '/materi/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/articles/$slug'
    | '/materi/$slug'
    | '/portfolio/$slug'
    | '/articles'
    | '/materi'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/contact'
    | '/materi'
    | '/portfolio'
    | '/services'
    | '/articles/$slug'
    | '/materi/$slug'
    | '/portfolio/$slug'
    | '/articles/'
    | '/materi/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  MateriRoute: typeof MateriRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi': {
      id: '/materi'
      path: '/materi'
      fullPath: '/materi'
      preLoaderRoute: typeof MateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/materi/': {
      id: '/materi/'
      path: '/'
      fullPath: '/materi/'
      preLoaderRoute: typeof MateriIndexRouteImport
      parentRoute: typeof MateriRoute
    }
    '/materi/$slug': {
      id: '/materi/$slug'
      path: '/$slug'
      fullPath: '/materi/$slug'
      preLoaderRoute: typeof MateriSlugRouteImport
      parentRoute: typeof MateriRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface MateriRouteChildren {
  MateriSlugRoute: typeof MateriSlugRoute
  MateriIndexRoute: typeof MateriIndexRoute
}

const MateriRouteChildren: MateriRouteChildren = {
  MateriSlugRoute: MateriSlugRoute,
  MateriIndexRoute: MateriIndexRoute,
}

const MateriRouteWithChildren =
  MateriRoute._addFileChildren(MateriRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  MateriRoute: MateriRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
